apiVersion: v1
kind: Service
metadata:
  labels:
    name: stable
  name: app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: stable
