apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: stable
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: stable
    spec:
      containers:
        - image: gcr.io/ninneman_cvdev/app:latest
        name: stable
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: "/status"
            port: 8080
        resources:
          requests:
            memory: "100Mi"
        env:
          - name: MONGODB_URL
            value: "mongodb://mongo:27017/article_demo_dev"
